apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ms-payment-registry
  namespace: prod
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-ms-payment-registry
  template:
    metadata:
      labels:
        app: backend-ms-payment-registry
        version: "1.00"
    spec:
      containers:
        - name: backend-ms-payment-registry
          image: zebolhd/qa-backend-ms-payment-registry:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: qa-config
            - secretRef:
                name: qa-secret
